name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Execute deploy script on server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
          cd domains/taskpulse.tech/ || exit
          rm -rf *
          git clone https://github.com/wilsonneto-dev/demo-newrelic-php-hostinger
          mv ./demo-newrelic-php-hostinger/* ./
          mv ./demo-newrelic-php-hostinger/.* ./
          rm -rf ./demo-newrelic-php-hostinger/
          mv ../../demo-twitter.env ./.env
          ls -la
        EOF
